// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {WujiIndex} from "../src/WujiIndex.sol";
import {WujiTestBase} from "./Base.t.sol";

/// Real BSC block hashes, regenerated by scripts/check-real-hashes.sh, folded through the contract and
/// compared with the indexer's exact integer accumulator. If this passes, chain, indexer and contract agree.
contract WujiIndexRealHashes is WujiTestBase {
    function test_realHashesMatchIndexer() public {
        string memory path = "test/fixtures/real-hashes.json";
        if (!vm.exists(path)) { emit log("no fixture; run scripts/check-real-hashes.sh"); return; }
        string memory j = vm.readFile(path);
        uint64 from = uint64(vm.parseJsonUint(j, ".from"));
        uint64 to = uint64(vm.parseJsonUint(j, ".to"));
        bytes32[] memory hashes = vm.parseJsonBytes32Array(j, ".hashes");
        int256 expected = vm.parseInt(vm.parseJsonString(j, ".expectedSWad"));
        assertEq(hashes.length, to - from + 1);

        installHistory();
        vm.roll(to + 1);
        for (uint64 b = from; b <= to; b++) { vm.setBlockhash(b, hashes[b - from]); history.set(b, hashes[b - from]); }
        vm.roll(from);
        WujiIndex idx = new WujiIndex(from);
        vm.roll(to + 1);
        assertEq(idx.tick(), to - from + 1);
        emit log_named_int("contract S_wad", idx.S());
        emit log_named_int("indexer  S_wad", expected);
        assertEq(idx.S(), expected);
    }
}
